name: Hello Workflow

on: [push]

jobs:
  myjob:
    name: Hello Job
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - name: Hello Step
      run: echo "Yeah babe"
    - name: Print env
      run: env | sort
    - name: Python Syntax Checker
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
